# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  apple-emoji = {
    pname = "apple-emoji";
    version = "https://github.com/samuelngs/apple-emoji-linux/releases/latest/download/AppleColorEmoji-Linux.ttf";
    src = fetchurl {
      url = "https://github.com/samuelngs/apple-emoji-linux/releases/latest/download/AppleColorEmoji-Linux.ttf";
      sha256 = "sha256-U1oEOvBHBtJEcQWeZHRb/IDWYXraLuo0NdxWINwPUxg=";
    };
  };
  colorscheme = {
    pname = "colorscheme";
    version = "5f868b3a338b6904c47f3833b9c411be641983a8";
    src = fetchFromGitHub {
      owner = "tinted-theming";
      repo = "schemes";
      rev = "5f868b3a338b6904c47f3833b9c411be641983a8";
      fetchSubmodules = false;
      sha256 = "sha256-BAGZ7ObFV/9Z61OJZun7ifPyhkuHqNuW1QIhQ8LuzCo=";
    };
    date = "2026-04-24";
  };
  fish-completion-sync = {
    pname = "fish-completion-sync";
    version = "4f058ad2986727a5f510e757bc82cbbfca4596f0";
    src = fetchFromGitHub {
      owner = "iynaix";
      repo = "fish-completion-sync";
      rev = "4f058ad2986727a5f510e757bc82cbbfca4596f0";
      fetchSubmodules = false;
      sha256 = "sha256-kHpdCQdYcpvi9EFM/uZXv93mZqlk1zCi2DRhWaDyK5g=";
    };
    date = "2025-03-09";
  };
  fuzzy-search-src = {
    pname = "fuzzy-search-src";
    version = "16cea088a39c7769fbd22c4810347b04dd38c6b2";
    src = fetchFromGitHub {
      owner = "onelocked";
      repo = "fuzzy-search.yazi";
      rev = "16cea088a39c7769fbd22c4810347b04dd38c6b2";
      fetchSubmodules = false;
      sha256 = "sha256-3YsZQ7SOkJZfUWP2KGzp8fPpT42M+x2aThs/AYmdy0o=";
    };
    date = "2026-03-25";
  };
  hand-of-evil = {
    pname = "hand-of-evil";
    version = "https://github.com/Grief/hand-of-evil/releases/download/v1.2/hand-of-evil.tar.gz";
    src = fetchTarball {
      url = "https://github.com/Grief/hand-of-evil/releases/download/v1.2/hand-of-evil.tar.gz";
      sha256 = "sha256-tZn+GCKOQqM+EYSzxF2qKHPHa1xgewAnedG/jaoDoVE=";
    };
  };
  miku = {
    pname = "miku";
    version = "471ff88156e9a3dc8542d23e8cae4e1c9de6e732";
    src = fetchFromGitHub {
      owner = "supermariofps";
      repo = "hatsune-miku-windows-linux-cursors";
      rev = "471ff88156e9a3dc8542d23e8cae4e1c9de6e732";
      fetchSubmodules = false;
      sha256 = "sha256-HCHo4GwWLvjjnKWNiHb156Z+NQqliqLX1T1qNxMEMfE=";
    };
    date = "2025-03-13";
  };
  niri-shaders-collection = {
    pname = "niri-shaders-collection";
    version = "aa26f4e157b818630cb281f6e1968b641c079d69";
    src = fetchFromGitHub {
      owner = "jgarza9788";
      repo = "niri-animation-collection";
      rev = "aa26f4e157b818630cb281f6e1968b641c079d69";
      fetchSubmodules = false;
      sha256 = "sha256-DgoudR6etn+t5eYplPcOISPuWMRAulW6ZOCTsyFHi2w=";
    };
    date = "2026-04-07";
  };
  otter-launcher = {
    pname = "otter-launcher";
    version = "ae647cef5b3c3dd52bedd7a8c881988e412a2dca";
    src = fetchFromGitHub {
      owner = "kuokuo123";
      repo = "otter-launcher";
      rev = "ae647cef5b3c3dd52bedd7a8c881988e412a2dca";
      fetchSubmodules = false;
      sha256 = "sha256-ImJeI5xbd/w4nchFwc0tSS8v2vYWx/ttwM5uk2BWsCk=";
    };
    date = "2026-04-23";
  };
  tokyonight = {
    pname = "tokyonight";
    version = "cdc07ac78467a233fd62c493de29a17e0cf2b2b6";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "tokyonight.nvim";
      rev = "cdc07ac78467a233fd62c493de29a17e0cf2b2b6";
      fetchSubmodules = false;
      sha256 = "sha256-a9iRWue7DB7s/wNdxqqB51Jya5P9X6sDftqhdmKggU0=";
    };
    date = "2026-03-24";
  };
  tokyonight-vesktop-theme = {
    pname = "tokyonight-vesktop-theme";
    version = "585302fe074249eff2212930d26b0153a5ff5102";
    src = fetchFromGitHub {
      owner = "ForRealy";
      repo = "Tokyo-Night-fixed";
      rev = "585302fe074249eff2212930d26b0153a5ff5102";
      fetchSubmodules = false;
      sha256 = "sha256-iipzyCRE6XbOERlcxRj8Vdbx0lN66XZ7wNJgexeoAcM=";
    };
    date = "2025-06-22";
  };
  tokyonight-yazi-theme = {
    pname = "tokyonight-yazi-theme";
    version = "70fe6b4a245a59b546166aae6c45ee2b471869c2";
    src = fetchFromGitHub {
      owner = "kalidyasin";
      repo = "yazi-flavors";
      rev = "70fe6b4a245a59b546166aae6c45ee2b471869c2";
      fetchSubmodules = false;
      sha256 = "sha256-9I6NWIlNi4y0mNuqX8AbjfIK9vrC3+fzP0dJdh6QAic=";
    };
    date = "2026-01-26";
  };
  yazi-plugins-repo = {
    pname = "yazi-plugins-repo";
    version = "ac82af3e10f9a32cecd9f87ac64b3f9de7c7aea7";
    src = fetchFromGitHub {
      owner = "yazi-rs";
      repo = "plugins";
      rev = "ac82af3e10f9a32cecd9f87ac64b3f9de7c7aea7";
      fetchSubmodules = false;
      sha256 = "sha256-svc7I2E+tVMEUWUvIS6i3oTGfLq13eaI61T0c1MQ8qQ=";
    };
    date = "2026-04-23";
  };
}
