[all_follow]
flake-compat = "flake-compat"
flake-utils = "flake-utils"
nixpkgs = "nixpkgs"
rust-overlay = "rust-overlay"
systems = "systems"
treefmt-nix = "treefmt-nix"

[inputs.apple-fonts]
url = "gh:Lyndeno/apple-fonts.nix"

[inputs.base16]
url = "gh:senchopens/base16.nix"

[inputs.bat-syntax-justfile]
type = "fetch"
url = "gh:nk9/just_sublime"

[inputs.birdee]
url = "gh:BirdeeHub/nix-wrapper-modules"

[inputs.chicago-font]
type = "fetch"
url = "gh:nikdog/chicago-font"

[inputs.crtty]
type = "fetch"
url = "gh:kosa12/CRTty"

[inputs.extra-metadata]
type = "fetch"
url = "gh:boydaihungst/file-extra-metadata.yazi"

[inputs.fish-completion-sync]
type = "fetch"
url = "gh:iynaix/fish-completion-sync"

[inputs.fragment-mono]
type = "fetch"
url = "gh:dtinth/fragment-mono-weights"

[inputs.fsel]
type = "fetch"
url = "gh:Mjoyufull/fsel"

[inputs.helvetica-font]
type = "fetch"
url = "gh:Kyles-World/Helvetica-Font"

[inputs.hjem]
url = "gh:feel-co/hjem"

[inputs.hyprland]
url = "gh:hyprwm/Hyprland"

[inputs.neovim]
url = "path:/home/wyspr/Configuration/Neovim/"

[inputs.nix-cachyos-kernel]
exclude_follow = ["nixpkgs"]
url = "gh:xddxdd/nix-cachyos-kernel/release"

[inputs.nix-gaming-edge]
url = "gh:powerofthe69/nix-gaming-edge"

[inputs.nix-index-database]
url = "gh:nix-community/nix-index-database"

[inputs.nixos-core]
url = "gh:manic-systems/nixos-core/refs/tags/v1.0.1"

[inputs.nixpkgs]
url = "nixpkgs:unstable"

[inputs.otter-launcher]
type = "fetch"
url = "gh:kuokuo123/otter-launcher"

[inputs.pixprint]
url = "gh:preprocessor/pixprint"

[inputs.sops-nix]
url = "gh:Mic92/sops-nix"

[inputs.tack]
url = "gh:manic-systems/tack"

[inputs.yazi]
url = "gh:sxyazi/yazi"

[inputs.yazi-fuzzy-search]
type = "fetch"
url = "gh:onelocked/fuzzy-search.yazi"

[inputs.yazi-no-header]
type = "fetch"
url = "gh:onelocked/no-header-prompt.yazi"

[inputs.yazi-plugins]
type = "fetch"
url = "gh:AminurAlam/yazi-plugins"

[inputs.yaziline]
type = "fetch"
url = "gh:llanosrocas/yaziline.yazi"

[shorturls]
gh = "github:{path}"
nixpkgs = "github:NixOS/nixpkgs/nixpkgs-{path}"
path = "git+file:///{path}"
