# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  colorscheme = {
    pname = "colorscheme";
    version = "0c94645546f4f3ddac77a1a5fce54eb95bf50795";
    src = fetchFromGitHub {
      owner = "tinted-theming";
      repo = "schemes";
      rev = "0c94645546f4f3ddac77a1a5fce54eb95bf50795";
      fetchSubmodules = false;
      sha256 = "sha256-PDF0/wObw4nIsSBeXVYLsloXOiphXCgIdsrNcVXguKs=";
    };
    date = "2026-05-03";
  };
  fish-completion-sync = {
    pname = "fish-completion-sync";
    version = "4f058ad2986727a5f510e757bc82cbbfca4596f0";
    src = fetchFromGitHub {
      owner = "iynaix";
      repo = "fish-completion-sync";
      rev = "4f058ad2986727a5f510e757bc82cbbfca4596f0";
      fetchSubmodules = false;
      sha256 = "sha256-kHpdCQdYcpvi9EFM/uZXv93mZqlk1zCi2DRhWaDyK5g=";
    };
    date = "2025-03-09";
  };
  fsel = {
    pname = "fsel";
    version = "6b6ae52e3a2c254007e8a2c332a8d5de99428ba5";
    src = fetchFromGitHub {
      owner = "Mjoyufull";
      repo = "fsel";
      rev = "6b6ae52e3a2c254007e8a2c332a8d5de99428ba5";
      fetchSubmodules = false;
      sha256 = "sha256-7YoRc6jOuQUI0yv3qBHFhc60G/RG0LwVsKkN90UkPn4=";
    };
    date = "2026-05-17";
  };
  fuzzy-search-src = {
    pname = "fuzzy-search-src";
    version = "8adfa1778e51c6b42867836304c9af74a0c41b58";
    src = fetchFromGitHub {
      owner = "onelocked";
      repo = "fuzzy-search.yazi";
      rev = "8adfa1778e51c6b42867836304c9af74a0c41b58";
      fetchSubmodules = false;
      sha256 = "sha256-4z1FpHlzm+YFHlvZYJGWXp7AQlOwkF9d+rsP4BgTReY=";
    };
    date = "2026-05-22";
  };
  hand-of-evil = {
    pname = "hand-of-evil";
    version = "https://github.com/Grief/hand-of-evil/releases/download/v1.2/hand-of-evil.tar.gz";
    src = fetchTarball {
      url = "https://github.com/Grief/hand-of-evil/releases/download/v1.2/hand-of-evil.tar.gz";
      sha256 = "sha256-tZn+GCKOQqM+EYSzxF2qKHPHa1xgewAnedG/jaoDoVE=";
    };
  };
  miku = {
    pname = "miku";
    version = "471ff88156e9a3dc8542d23e8cae4e1c9de6e732";
    src = fetchFromGitHub {
      owner = "supermariofps";
      repo = "hatsune-miku-windows-linux-cursors";
      rev = "471ff88156e9a3dc8542d23e8cae4e1c9de6e732";
      fetchSubmodules = false;
      sha256 = "sha256-HCHo4GwWLvjjnKWNiHb156Z+NQqliqLX1T1qNxMEMfE=";
    };
    date = "2025-03-13";
  };
  niri-shaders-collection = {
    pname = "niri-shaders-collection";
    version = "aa26f4e157b818630cb281f6e1968b641c079d69";
    src = fetchFromGitHub {
      owner = "jgarza9788";
      repo = "niri-animation-collection";
      rev = "aa26f4e157b818630cb281f6e1968b641c079d69";
      fetchSubmodules = false;
      sha256 = "sha256-DgoudR6etn+t5eYplPcOISPuWMRAulW6ZOCTsyFHi2w=";
    };
    date = "2026-04-07";
  };
  otter-launcher = {
    pname = "otter-launcher";
    version = "b1c2c0992403f52dff1f5754cc250ee6e121e342";
    src = fetchFromGitHub {
      owner = "kuokuo123";
      repo = "otter-launcher";
      rev = "b1c2c0992403f52dff1f5754cc250ee6e121e342";
      fetchSubmodules = false;
      sha256 = "sha256-D3wp7vR3+ktTNJ54rUWHIK6Y5tGeNXDD4FBO785wl0E=";
    };
    date = "2026-05-19";
  };
  tokyonight = {
    pname = "tokyonight";
    version = "cdc07ac78467a233fd62c493de29a17e0cf2b2b6";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "tokyonight.nvim";
      rev = "cdc07ac78467a233fd62c493de29a17e0cf2b2b6";
      fetchSubmodules = false;
      sha256 = "sha256-a9iRWue7DB7s/wNdxqqB51Jya5P9X6sDftqhdmKggU0=";
    };
    date = "2026-03-24";
  };
  tokyonight-vesktop-theme = {
    pname = "tokyonight-vesktop-theme";
    version = "585302fe074249eff2212930d26b0153a5ff5102";
    src = fetchFromGitHub {
      owner = "ForRealy";
      repo = "Tokyo-Night-fixed";
      rev = "585302fe074249eff2212930d26b0153a5ff5102";
      fetchSubmodules = false;
      sha256 = "sha256-iipzyCRE6XbOERlcxRj8Vdbx0lN66XZ7wNJgexeoAcM=";
    };
    date = "2025-06-22";
  };
  tokyonight-yazi-theme = {
    pname = "tokyonight-yazi-theme";
    version = "70fe6b4a245a59b546166aae6c45ee2b471869c2";
    src = fetchFromGitHub {
      owner = "kalidyasin";
      repo = "yazi-flavors";
      rev = "70fe6b4a245a59b546166aae6c45ee2b471869c2";
      fetchSubmodules = false;
      sha256 = "sha256-9I6NWIlNi4y0mNuqX8AbjfIK9vrC3+fzP0dJdh6QAic=";
    };
    date = "2026-01-26";
  };
  yazi-plugins-repo = {
    pname = "yazi-plugins-repo";
    version = "be524fb140206cc59b3e51037ba6148935263975";
    src = fetchFromGitHub {
      owner = "yazi-rs";
      repo = "plugins";
      rev = "be524fb140206cc59b3e51037ba6148935263975";
      fetchSubmodules = false;
      sha256 = "sha256-QacgLcTG8uFqEyRQdyIUt4QKZOc81vV5iXKmR8sqV3c=";
    };
    date = "2026-05-23";
  };
}
