# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  chicago-font = {
    pname = "chicago-font";
    version = "ad613ccf9e356035187a377618f0f552963e18b7";
    src = fetchFromGitHub {
      owner = "nikdog";
      repo = "chicago-font";
      rev = "ad613ccf9e356035187a377618f0f552963e18b7";
      fetchSubmodules = false;
      sha256 = "sha256-M49oTUSc1jTmO2npx96wGYEopZU3+ql9L7mGm2rbzzM=";
    };
    date = "2025-07-27";
  };
  extra-metadata = {
    pname = "extra-metadata";
    version = "044274ca2e473f18910d03ca7392dff5ef028deb";
    src = fetchFromGitHub {
      owner = "boydaihungst";
      repo = "file-extra-metadata.yazi";
      rev = "044274ca2e473f18910d03ca7392dff5ef028deb";
      fetchSubmodules = false;
      sha256 = "sha256-Yq8nv/MSxOy0xTyeIQac/Gu8j1tLL6m7glFicjJ3fIs=";
    };
    date = "2026-04-22";
  };
  fish-completion-sync = {
    pname = "fish-completion-sync";
    version = "4f058ad2986727a5f510e757bc82cbbfca4596f0";
    src = fetchFromGitHub {
      owner = "iynaix";
      repo = "fish-completion-sync";
      rev = "4f058ad2986727a5f510e757bc82cbbfca4596f0";
      fetchSubmodules = false;
      sha256 = "sha256-kHpdCQdYcpvi9EFM/uZXv93mZqlk1zCi2DRhWaDyK5g=";
    };
    date = "2025-03-09";
  };
  fsel = {
    pname = "fsel";
    version = "8a12d4f35e78297f3e2d55e026185710bff38338";
    src = fetchFromGitHub {
      owner = "Mjoyufull";
      repo = "fsel";
      rev = "8a12d4f35e78297f3e2d55e026185710bff38338";
      fetchSubmodules = false;
      sha256 = "sha256-XGKD/DId5Eont4ytPV7LfGvykDRalMWx4pbkRVUNzxY=";
    };
    date = "2026-06-14";
  };
  hand-of-evil = {
    pname = "hand-of-evil";
    version = "https://github.com/Grief/hand-of-evil/releases/download/v1.2/hand-of-evil.tar.gz";
    src = fetchTarball {
      url = "https://github.com/Grief/hand-of-evil/releases/download/v1.2/hand-of-evil.tar.gz";
      sha256 = "sha256-tZn+GCKOQqM+EYSzxF2qKHPHa1xgewAnedG/jaoDoVE=";
    };
  };
  helvetica-font = {
    pname = "helvetica-font";
    version = "26bef19d2b9f3a8d1194629760ca1c0e14185d93";
    src = fetchFromGitHub {
      owner = "Kyles-World";
      repo = "Helvetica-Font";
      rev = "26bef19d2b9f3a8d1194629760ca1c0e14185d93";
      fetchSubmodules = false;
      sha256 = "sha256-EyqFPfjPGvQ1GIo3/4aTYum1tJRgVYqTmypgzj9T0BI=";
    };
    date = "2026-06-02";
  };
  miku = {
    pname = "miku";
    version = "471ff88156e9a3dc8542d23e8cae4e1c9de6e732";
    src = fetchFromGitHub {
      owner = "supermariofps";
      repo = "hatsune-miku-windows-linux-cursors";
      rev = "471ff88156e9a3dc8542d23e8cae4e1c9de6e732";
      fetchSubmodules = false;
      sha256 = "sha256-HCHo4GwWLvjjnKWNiHb156Z+NQqliqLX1T1qNxMEMfE=";
    };
    date = "2025-03-13";
  };
  otter-launcher = {
    pname = "otter-launcher";
    version = "764a38d1de308da3268222692652a0a85bb71eee";
    src = fetchFromGitHub {
      owner = "kuokuo123";
      repo = "otter-launcher";
      rev = "764a38d1de308da3268222692652a0a85bb71eee";
      fetchSubmodules = false;
      sha256 = "sha256-vlNT2248Oxg3++bk8ZkozsU4wDbxOkh6dl3GeoBmmXE=";
    };
    date = "2026-06-09";
  };
  schemes = {
    pname = "schemes";
    version = "2ccef2f4b22e3cab5a9292811f7133a07eeba4a7";
    src = fetchFromGitHub {
      owner = "tinted-theming";
      repo = "schemes";
      rev = "2ccef2f4b22e3cab5a9292811f7133a07eeba4a7";
      fetchSubmodules = false;
      sha256 = "sha256-yYO3Vw2M0y3TAUqt+9+Mj0zwP3XDTF5/PXcPhhFQ1ZM=";
    };
    date = "2026-06-20";
  };
  yaziline = {
    pname = "yaziline";
    version = "25161c18e61339b6a79f29f8948e3c360e3f9ace";
    src = fetchFromGitHub {
      owner = "llanosrocas";
      repo = "yaziline.yazi";
      rev = "25161c18e61339b6a79f29f8948e3c360e3f9ace";
      fetchSubmodules = false;
      sha256 = "sha256-gF21K8Sn9VFh6nKcM5dhTiAH1sOE9D/Gmc8i3J8m+S4=";
    };
    date = "2026-05-09";
  };
}
