# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  extra-metadata = {
    pname = "extra-metadata";
    version = "044274ca2e473f18910d03ca7392dff5ef028deb";
    src = fetchFromGitHub {
      owner = "boydaihungst";
      repo = "file-extra-metadata.yazi";
      rev = "044274ca2e473f18910d03ca7392dff5ef028deb";
      fetchSubmodules = false;
      sha256 = "sha256-Yq8nv/MSxOy0xTyeIQac/Gu8j1tLL6m7glFicjJ3fIs=";
    };
    date = "2026-04-22";
  };
  eza-themes = {
    pname = "eza-themes";
    version = "add4c72c546992b8db674d6d3eea315bf2111b9a";
    src = fetchFromGitHub {
      owner = "eza-community";
      repo = "eza-themes";
      rev = "add4c72c546992b8db674d6d3eea315bf2111b9a";
      fetchSubmodules = false;
      sha256 = "sha256-toqj3bv2kCC2FHbGfeFpS3g9DoxQeZ7cwPYVpD8cfgg=";
    };
    date = "2026-03-04";
  };
  fish-completion-sync = {
    pname = "fish-completion-sync";
    version = "4f058ad2986727a5f510e757bc82cbbfca4596f0";
    src = fetchFromGitHub {
      owner = "iynaix";
      repo = "fish-completion-sync";
      rev = "4f058ad2986727a5f510e757bc82cbbfca4596f0";
      fetchSubmodules = false;
      sha256 = "sha256-kHpdCQdYcpvi9EFM/uZXv93mZqlk1zCi2DRhWaDyK5g=";
    };
    date = "2025-03-09";
  };
  fsel = {
    pname = "fsel";
    version = "6b6ae52e3a2c254007e8a2c332a8d5de99428ba5";
    src = fetchFromGitHub {
      owner = "Mjoyufull";
      repo = "fsel";
      rev = "6b6ae52e3a2c254007e8a2c332a8d5de99428ba5";
      fetchSubmodules = false;
      sha256 = "sha256-7YoRc6jOuQUI0yv3qBHFhc60G/RG0LwVsKkN90UkPn4=";
    };
    date = "2026-05-17";
  };
  fuzzy-search-src = {
    pname = "fuzzy-search-src";
    version = "7be2437b45be1da9b3be0ed2f244709c9b9be242";
    src = fetchFromGitHub {
      owner = "onelocked";
      repo = "fuzzy-search.yazi";
      rev = "7be2437b45be1da9b3be0ed2f244709c9b9be242";
      fetchSubmodules = false;
      sha256 = "sha256-vW6o5vbYXr++cFAcyvl7E2tYHQMV5lGK2rEOG5iiRPg=";
    };
    date = "2026-05-25";
  };
  gruvbox = {
    pname = "gruvbox";
    version = "5bfe85a961d144376f9f9460f2b2a85343a0f0b3";
    src = fetchFromGitHub {
      owner = "gruvbox-community";
      repo = "gruvbox-contrib";
      rev = "5bfe85a961d144376f9f9460f2b2a85343a0f0b3";
      fetchSubmodules = false;
      sha256 = "sha256-9rYLbnQZV+sTJdYwEZlqJzGHC2w/z9MUWzJr474B834=";
    };
    date = "2023-09-11";
  };
  gruvbox-discord = {
    pname = "gruvbox-discord";
    version = "https://raw.githubusercontent.com/round-panda/gruvbox-sharp/main/GruvboxSharp.theme.css";
    src = fetchurl {
      url = "https://raw.githubusercontent.com/round-panda/gruvbox-sharp/main/GruvboxSharp.theme.css";
      sha256 = "sha256-fRj80A/foM6Bc6odECU2JuYrLhxuknbqot7QL3TUqWo=";
    };
  };
  gruvbox-fish = {
    pname = "gruvbox-fish";
    version = "b3c8fd52e6d3860123cc1c3a8b72e12d887596ba";
    src = fetchFromGitHub {
      owner = "gruvbox-community";
      repo = "fish-gruvbox";
      rev = "b3c8fd52e6d3860123cc1c3a8b72e12d887596ba";
      fetchSubmodules = false;
      sha256 = "sha256-LhBerkaPfKMmmb29EoYdpMxWc3ckFesaty15M2SCO7Y=";
    };
    date = "2019-06-01";
  };
  gruvbox-lazygit = {
    pname = "gruvbox-lazygit";
    version = "2ed4a23ca050987e6283a2a9bce348b3288591d7";
    src = fetchFromGitHub {
      owner = "im-AMS";
      repo = "gruvbox-material-lazygit";
      rev = "2ed4a23ca050987e6283a2a9bce348b3288591d7";
      fetchSubmodules = false;
      sha256 = "sha256-jfVgHetavAr1jTjA+Ivg/LXDWQBqqmc3mtNBi1w0C/0=";
    };
    date = "2025-12-27";
  };
  hand-of-evil = {
    pname = "hand-of-evil";
    version = "https://github.com/Grief/hand-of-evil/releases/download/v1.2/hand-of-evil.tar.gz";
    src = fetchTarball {
      url = "https://github.com/Grief/hand-of-evil/releases/download/v1.2/hand-of-evil.tar.gz";
      sha256 = "sha256-tZn+GCKOQqM+EYSzxF2qKHPHa1xgewAnedG/jaoDoVE=";
    };
  };
  miku = {
    pname = "miku";
    version = "471ff88156e9a3dc8542d23e8cae4e1c9de6e732";
    src = fetchFromGitHub {
      owner = "supermariofps";
      repo = "hatsune-miku-windows-linux-cursors";
      rev = "471ff88156e9a3dc8542d23e8cae4e1c9de6e732";
      fetchSubmodules = false;
      sha256 = "sha256-HCHo4GwWLvjjnKWNiHb156Z+NQqliqLX1T1qNxMEMfE=";
    };
    date = "2025-03-13";
  };
  niri-shaders-collection = {
    pname = "niri-shaders-collection";
    version = "aa26f4e157b818630cb281f6e1968b641c079d69";
    src = fetchFromGitHub {
      owner = "jgarza9788";
      repo = "niri-animation-collection";
      rev = "aa26f4e157b818630cb281f6e1968b641c079d69";
      fetchSubmodules = false;
      sha256 = "sha256-DgoudR6etn+t5eYplPcOISPuWMRAulW6ZOCTsyFHi2w=";
    };
    date = "2026-04-07";
  };
  no-header = {
    pname = "no-header";
    version = "dd34339092b7cdc1f8213017f939e55e0b47a008";
    src = fetchFromGitHub {
      owner = "onelocked";
      repo = "no-header-prompt.yazi";
      rev = "dd34339092b7cdc1f8213017f939e55e0b47a008";
      fetchSubmodules = false;
      sha256 = "sha256-dHJNk3o9vMGUnO/KAl7R6UdEq1giyp2DNXzxmAKBZP0=";
    };
    date = "2026-05-25";
  };
  otter-launcher = {
    pname = "otter-launcher";
    version = "b1c2c0992403f52dff1f5754cc250ee6e121e342";
    src = fetchFromGitHub {
      owner = "kuokuo123";
      repo = "otter-launcher";
      rev = "b1c2c0992403f52dff1f5754cc250ee6e121e342";
      fetchSubmodules = false;
      sha256 = "sha256-D3wp7vR3+ktTNJ54rUWHIK6Y5tGeNXDD4FBO785wl0E=";
    };
    date = "2026-05-19";
  };
  retrowave-light-kitty = {
    pname = "retrowave-light-kitty";
    version = "https://github.com/BrokenSideViewMirror/kitty-themes/blob/master/themes/retrowave-light.conf";
    src = fetchurl {
      url = "https://github.com/BrokenSideViewMirror/kitty-themes/blob/master/themes/retrowave-light.conf";
      sha256 = "sha256-aznDMBrV3qemQsgEDjRlveo1SGqeG3g16nIJ3BwEyVs=";
    };
  };
  schemes = {
    pname = "schemes";
    version = "0c94645546f4f3ddac77a1a5fce54eb95bf50795";
    src = fetchFromGitHub {
      owner = "tinted-theming";
      repo = "schemes";
      rev = "0c94645546f4f3ddac77a1a5fce54eb95bf50795";
      fetchSubmodules = false;
      sha256 = "sha256-PDF0/wObw4nIsSBeXVYLsloXOiphXCgIdsrNcVXguKs=";
    };
    date = "2026-05-03";
  };
  tokyonight = {
    pname = "tokyonight";
    version = "cdc07ac78467a233fd62c493de29a17e0cf2b2b6";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "tokyonight.nvim";
      rev = "cdc07ac78467a233fd62c493de29a17e0cf2b2b6";
      fetchSubmodules = false;
      sha256 = "sha256-a9iRWue7DB7s/wNdxqqB51Jya5P9X6sDftqhdmKggU0=";
    };
    date = "2026-03-24";
  };
  tokyonight-vesktop-theme = {
    pname = "tokyonight-vesktop-theme";
    version = "585302fe074249eff2212930d26b0153a5ff5102";
    src = fetchFromGitHub {
      owner = "ForRealy";
      repo = "Tokyo-Night-fixed";
      rev = "585302fe074249eff2212930d26b0153a5ff5102";
      fetchSubmodules = false;
      sha256 = "sha256-iipzyCRE6XbOERlcxRj8Vdbx0lN66XZ7wNJgexeoAcM=";
    };
    date = "2025-06-22";
  };
  tokyonight-yazi-theme = {
    pname = "tokyonight-yazi-theme";
    version = "70fe6b4a245a59b546166aae6c45ee2b471869c2";
    src = fetchFromGitHub {
      owner = "kalidyasin";
      repo = "yazi-flavors";
      rev = "70fe6b4a245a59b546166aae6c45ee2b471869c2";
      fetchSubmodules = false;
      sha256 = "sha256-9I6NWIlNi4y0mNuqX8AbjfIK9vrC3+fzP0dJdh6QAic=";
    };
    date = "2026-01-26";
  };
  yaziline = {
    pname = "yaziline";
    version = "25161c18e61339b6a79f29f8948e3c360e3f9ace";
    src = fetchFromGitHub {
      owner = "llanosrocas";
      repo = "yaziline.yazi";
      rev = "25161c18e61339b6a79f29f8948e3c360e3f9ace";
      fetchSubmodules = false;
      sha256 = "sha256-gF21K8Sn9VFh6nKcM5dhTiAH1sOE9D/Gmc8i3J8m+S4=";
    };
    date = "2026-05-09";
  };
}
